### ISSUE TITLE
redesign and finalize for loop variables

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#116]
- rethink and redesign the UI to include the counter variable (moved to #136)
- do we want to include multiple variables? e.g. `for key, val in dictionary:` or just ignore this for now? (Discussed in meeting on 29/06/21, No)
- refactor and move validation to validator (should be under #123.)
- <del>add the counter variable to the suggestion menu </del>
- <del>merge `addLoopVariableButtonToToolbox()` and `addVariableButtonToToolbox()` </del>

**Comment by MajeedKazemi** [comment]
urgency: 5
dependency: 3

**Comment by vicchig** [comment]
#132 and #131 address point number 4 and add the counter variables to the suggestions.

**Comment by vicchig** [comment]
@MajeedKazemi 

1. Could you clarify what you meant by the UI redesign? Were you thinking of adding a different section for the counter variables in the toolbox?

2. I would say we don't want multiple variables to be included in the definition. Novices usually don't encounter dictionaries for a while. However, if we do want this the implementation should be simple. Do what I did with the current single counter variable, but for all of them and convert <code>loopVar</code> of <code>ForStatement</code> into a list that holds all of the counters.

3. I think we should move point 3 under the validator issue. It belongs there in my opinion, otherwise this one won't be closed for a while even after all the other points are implemented.
