### ISSUE TITLE
type-checker incorrectly sets type to any (thinks it is unknown) while it could've never been changed

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#428]
in the example below `x` should still be a number, but it thinks that it might not still be a number because in the above if case it could've changed. however, only one of these two conditions will run:
![image](https://user-images.githubusercontent.com/57059538/137805335-61d0391d-759d-47fb-a2ad-7e1f19d10218.png)

**Comment by vicchig** [comment]
This is one of those interesting cases where we actually need to execute the program up until a certain point to determine what the type of the variable will be below the if block. Well, we don't _have_ to execute the program in this particular case since it is simple, but a simple case can quickly become quite complex as can be seen by some of the cases I go over below. We decided to leave it as any since it cannot easily be determined in all cases, but there are cases such as this one where it is fairly easy to tell that the type won't change. 

However, consider what it requires even in this simple case. 

**Case 1: All conditions in the if block are false.**
 - Then we are good as the type could not have changed.

**Case 2: At least one condition is true**
 - We need to adjust the type based on what happens inside the topmost statement that has a condition that evaluates to true. 
 - Inside that block we need to check if any assignments to our variable are even made and if any are made, adjust the type. 
   - This is actually pretty easy since we can just call `getTypeOfVarNearLine()` at the last line of the block

The cases are easy if there is an easy way of evaluating the truth value of each condition. However, this gets complicated really fast. Consider a condition such as `x.find('a') > -1`. Here is what can happen.

**Case 1: x is a static string**
  - assuming we can tell that it does not change
  - we still need to actually run the code or some pseudo `find()` on the value of `x` ourselves to be able to tell what the truth value is when the program reaches it.

**Case 2: x has multiple possible values based on execution paths before the if statement is reached**
 - this could be solved by actually running the code in Pyodide while the user is writing it and evaluating truth values of such conditions.
 - It is possible and I think it is really cool, but there are some issues:
   - Performance - how often do we perform these checks? Python is not the fastest language and web Python is probably even less so. Our code too has a lot of unoptimized places.
   - We need to modify the script that is ran to give us the results we want since running the user code won't do it.
     - What if user code is incomplete?
     - What if user code is complete, but has errors?

**Case 3: x is randomly generated**
 - :)

@MajeedKazemi please let me know what you think. I can definitely add something for the simple cases such as the one above, but it will in no way be comprehensive.
