### ISSUE TITLE
High Priority: Fixing removed variable instances when redefined

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#462]

**Comment by vicchig** [comment]
@MajeedKazemi 

Could you please provide more info on this one? I am not sure what it refers to.

**Comment by MajeedKazemi** [comment]
1. at first we have multiple instances of a variable:
![image](https://user-images.githubusercontent.com/57059538/140194547-decb5645-11c2-4db6-ac05-97782442b2a2.png)
2. the variable's declaration is deleted:
![image](https://user-images.githubusercontent.com/57059538/140194629-af663084-c02b-4985-a0a4-624f05fca47f.png)
3. finally, after I've redefined the variable `guess` I expected the errors to be gone, but they were still there:
![image](https://user-images.githubusercontent.com/57059538/140194658-f57cbdae-63ae-4223-8d1d-339adc6c1742.png)

**Comment by vicchig** [comment]
I see, thanks. There are no checks for this case. I will add a function to run through redefined variables.

**Comment by vicchig** [comment]
The issue is that in the case that variable usages exists, the tool does not go through the tree to remove the warnings. This one is easy to fix.

The true problem of this is if I now redefine `guess` as a string, all of those variable references need to be updated to that type, which is again possible, but I also need to potentially create draft modes based on type mismatches as well. Now that last part is not so easy. 

One solution I was thinking about is to just go through the references and reinsert them so that it would trigger the type checks. I think this should be ok as long as it does not slow down the tool. What do you think @MajeedKazemi ? The alternative is to code separate checks to run when we redefine a variable.

**Comment by MajeedKazemi** [comment]
Yes, this could be a potential easy way of doing it. just reusing our own API ...
