### ISSUE TITLE
Do not create duplicate buttons when using the same variable names

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#88]
when the user creates a variable, and uses a name that resides in the current scope, we should not create a new button for it in the toolbox (the button for getting and accessing its value).

**Comment by vicchig** [comment]
Discussed this in meeting.

The best solution would be to separate variable assignment and declaration in the toolbox and the code so that we don't have one code construct representing both. This allows us to fix/implement the following easily:
  1. When user is declaring a new variable, notify them if they are using an existing identifier.
  2. When assigning a value to a declared variable, user is not able to change the identifier on the left-hand side of the = since that will be provided by the toolbox.
  3. Checks for creating new toolbox buttons or removing existing ones will not need to worry whether the user meant to assign a value to a variable or declare a new variable. The context will always be known since we will have different code constructs representing each situation.

**Comment by MajeedKazemi** [comment]
urgency: 5
dependency: 3 (it will change the way we create and maintain variable buttons)

**Comment by vicchig** [comment]
@MajeedKazemi 

For 2. do we want it to work this way? It will double the amount of toolbox buttons we have for variables since each one will have one for assignment and one for referencing that variable (currently this is the only one displayed for each var). 

What if instead we had a general button for variable assignment in the toolbox instead of creating one for each variable we declared? When the user attempts to assign a value to a declared variable we would run validation on the identifier they attempted to use (can select it from the toolbox for now, maybe later they can type it out). We only really need to check that it is in-scope. 

I would even argue that this is better for learning as well. It gets the student to really think that they are taking a value and assigning it to be represented by some name since they would have to perform both actions manually (selecting identifier and then assigning a value) as opposed to only assigning a value if we automatically provide a button for them.

I am just leaving this here as a suggestion. A potential problem with this approach is the amount of validation we would have to do. So far I only see scope checks as something we would have to do, but there might be other types of validation.

**Comment by vicchig** [comment]
Another issue is knowing if we are creating a new variable or modifying an old one and what needs to happen to the buttons in the toolbox in each case.

For example.

x = 1
y = ""

And then we change y to x. We need to remove the button for y since otherwise we will have two buttons for x after the update to the identifier. However, if we then change x back to y, now we need to recreate the button.

**Comment by vicchig** [comment]
Addressed by the new-variables rework. Duplicate buttons are impossible now as are duplicate variables.
