### ISSUE TITLE
Disable invalid buttons in the Toolbox based on the users's focus

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#89]
In order to prevent *completely wrong* inserts (e.g. a for statement inside an if condition), we can and have to disable those edits.

**Comment by vicchig** [comment]
This might overlap with the warning system since this is something it actually already checks. So if we end up implementing this, we can probably remove it from there since, if the button is disabled altogether, then there really is no way to make an invalid insert. 

Just wanted to mention this because we can reuse the code from the warning system for this to make the implementation faster.

**Q: How would this affect construct insertion with the keyboard? Do we disable some insertions based on context for the keyboard as well or do we leave the warning system intact to catch those?**

**Comment by MajeedKazemi** [comment]
Yes, so it'll be great if we could use the same code for the checks. I understand that it overlaps, but some of the cases should be completely disabled which I believe is not only the right thing to do, but an advantage of our tool compared to visual (drag-and-drop based) programming languages which are not able to run these checks (as they don't have enough information about the context and the user's focused position).

Regarding your question: The checks will simply limit what will be shown in the suggestion menu, so within a condition of an if statement, even if the user starts typing in `fo` it will not display a `for loop` as one of the suggestions. If there are no variables that start with `fo...`, then I guess we can ignore what the user is typing and revert any inserted characters in the condition.
